$script=Join-Path $PSScriptRoot '..\skill\codex-project-orchestrator\scripts\test-project-readiness.ps1'
$manager=Join-Path $PSScriptRoot '..\skill\codex-project-orchestrator\scripts\manage-workflow.ps1'
function New-ReadinessRepo([string]$Path,[string]$Branch='main'){
    New-Item -ItemType Directory -Path $Path|Out-Null
    &git -C $Path init -b $Branch|Out-Null;&git -C $Path config user.name test;&git -C $Path config user.email test@example.invalid
    Set-Content (Join-Path $Path '.gitignore') '.codex-orchestrator/';Set-Content (Join-Path $Path 'README.md') 'base'
    &git -C $Path add .gitignore README.md;&git -C $Path commit -m baseline|Out-Null
}
function Get-Readiness([string]$Path,[string]$Target='main'){@(&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $script -ProjectPath $Path -TargetBranch $Target)|Out-String|ConvertFrom-Json}
Describe 'existing project readiness preflight' {
    It 'reports a clean conventional repository as compatible' {$repo=Join-Path $TestDrive 'clean';New-ReadinessRepo $repo;$report=Get-Readiness $repo;$report.classification|Should Be 'compatible';$report.recommended_mode|Should Be 'full-integration';$report.summary.blockers|Should Be 0}
    It 'keeps a dirty repository in isolated development mode' {$repo=Join-Path $TestDrive 'dirty';New-ReadinessRepo $repo;Add-Content (Join-Path $repo 'README.md') 'dirty';$report=Get-Readiness $repo;$report.classification|Should Be 'isolated-only';@($report.findings|Where-Object{$_.code -eq 'working-tree-dirty'}).Count|Should Be 1}
    It 'blocks a non repository and a repository without commits' {$plain=Join-Path $TestDrive 'plain';New-Item -ItemType Directory $plain|Out-Null;(Get-Readiness $plain).classification|Should Be 'blocked';$empty=Join-Path $TestDrive 'empty';New-Item -ItemType Directory $empty|Out-Null;&git -C $empty init -b main|Out-Null;(Get-Readiness $empty).classification|Should Be 'blocked'}
    It 'blocks a project path below the repository root' {$repo=Join-Path $TestDrive 'mono';New-ReadinessRepo $repo;$child=Join-Path $repo 'apps\web';New-Item -ItemType Directory $child -Force|Out-Null;$report=Get-Readiness $child;$report.classification|Should Be 'blocked';@($report.findings|Where-Object{$_.code -eq 'project-not-repository-root'}).Count|Should Be 1}
    It 'warns when runtime state is not ignored and when the target branch differs' {$repo=Join-Path $TestDrive 'warnings';New-ReadinessRepo $repo develop;Set-Content (Join-Path $repo '.gitignore') '*.tmp';&git -C $repo add .gitignore;&git -C $repo commit -m 'test: remove state ignore'|Out-Null;$report=Get-Readiness $repo;$report.classification|Should Be 'isolated-only';@($report.findings|Where-Object{$_.code -eq 'state-directory-not-ignored'}).Count|Should Be 1;@($report.findings|Where-Object{$_.code -eq 'target-branch-missing'}).Count|Should Be 1}
    It 'blocks an unfinished Git operation without deleting its evidence' {$repo=Join-Path $TestDrive 'merge';New-ReadinessRepo $repo;$gitDir=(&git -C $repo rev-parse --absolute-git-dir).Trim();$marker=Join-Path $gitDir 'MERGE_HEAD';Set-Content $marker ('a'*40);$report=Get-Readiness $repo;$report.classification|Should Be 'blocked';@($report.repository.ongoing_operations)-contains'merge'|Should Be $true;Test-Path $marker|Should Be $true}
    It 'reports sparse checkout and an existing default worktree root' {$repo=Join-Path $TestDrive 'special';New-ReadinessRepo $repo;&git -C $repo config core.sparseCheckout true;$root=Join-Path (Join-Path $TestDrive '.codex-worktrees') 'special';New-Item -ItemType Directory $root -Force|Out-Null;$report=Get-Readiness $repo;@($report.repository.special_features)-contains'sparse-checkout'|Should Be $true;@($report.findings|Where-Object{$_.code -eq 'worktree-root-exists'}).Count|Should Be 1}
    It 'returns only one JSON document through the manager entry point' {$repo=Join-Path $TestDrive 'manager';New-ReadinessRepo $repo;$report=@(&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $manager -Action preflight -ProjectPath $repo)|Out-String|ConvertFrom-Json;$report.classification|Should Be 'compatible';[DateTime]$report.expires_at|Should Not BeNullOrEmpty}
    It 'requires and records a current compatible report before initializing a Git project' {$repo=Join-Path $TestDrive 'gated';New-ReadinessRepo $repo;$missing=@(&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $manager -Action initialize -ProjectPath $repo -WorkflowId WF-GATED 2>&1);$LASTEXITCODE|Should Not Be 0;($missing-join' ')|Should Match 'PREFLIGHT_REQUIRED';$reportPath=Join-Path $TestDrive 'gated-report.json';&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $manager -Action preflight -ProjectPath $repo|Set-Content -LiteralPath $reportPath -Encoding UTF8;&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $manager -Action initialize -ProjectPath $repo -WorkflowId WF-GATED -ControllerThreadId controller -PreflightPath $reportPath|Out-Null;$LASTEXITCODE|Should Be 0;$workflow=Get-Content (Join-Path $repo '.codex-orchestrator\workflow.json') -Raw -Encoding UTF8|ConvertFrom-Json;$workflow.state_version|Should Be 20;$workflow.project_readiness.report_sha256|Should Match '^[a-f0-9]{64}$'}
    It 'rejects a report when the repository changes after preflight' {$repo=Join-Path $TestDrive 'stale';New-ReadinessRepo $repo;$reportPath=Join-Path $TestDrive 'stale-report.json';&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $manager -Action preflight -ProjectPath $repo|Set-Content -LiteralPath $reportPath -Encoding UTF8;Add-Content (Join-Path $repo 'README.md') 'changed';$output=@(&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $manager -Action initialize -ProjectPath $repo -WorkflowId WF-STALE -PreflightPath $reportPath 2>&1);$LASTEXITCODE|Should Not Be 0;($output-join' ')|Should Match 'STALE_PREFLIGHT';Test-Path (Join-Path $repo '.codex-orchestrator')|Should Be $false}
}
